//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luig.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuigDevEntities : DbContext
    {
        public LuigDevEntities()
            : base("name=LuigDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkInProgress> WorkInProgresses { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<GENDER> GENDERs { get; set; }
        public virtual DbSet<HOUSE_ADDRESS> HOUSE_ADDRESS { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<ZIP> ZIPs { get; set; }
    }
}
