//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luig.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int EMP_NUM { get; set; }
        public string EMP_TITLE { get; set; }
        public string EMP_LNAME { get; set; }
        public string EMP_FNAME { get; set; }
        public string EMP_INITIAL { get; set; }
        public Nullable<System.DateTime> EMP_DOB { get; set; }
        public Nullable<System.DateTime> EMP_HIRE_DATE { get; set; }
        public string EMP_AREACODE { get; set; }
        public string EMP_PHONE { get; set; }
        public Nullable<int> EMP_MGR { get; set; }
    }
}
