//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luig.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE
    {
        public int INV_NUMBER { get; set; }
        public decimal LINE_NUMBER { get; set; }
        public string P_CODE { get; set; }
        public decimal LINE_UNITS { get; set; }
        public decimal LINE_PRICE { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
