//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luig.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.LINEs = new HashSet<LINE>();
        }
    
        public string P_CODE { get; set; }
        public string P_DESCRIPT { get; set; }
        public System.DateTime P_INDATE { get; set; }
        public int P_QOH { get; set; }
        public int P_MIN { get; set; }
        public decimal P_PRICE { get; set; }
        public decimal P_DISCOUNT { get; set; }
        public Nullable<int> V_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINE> LINEs { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
